---
title: "shiny_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(stringr)
library(forcats)
library(tidytext) 
library(ggridges)
library(shiny)
```

```{r}
library(httr)
library(jsonlite)
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() %>%
  mutate(score = as.numeric(score)) %>%
  filter(!is.na(score))
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
#Textinput widget
textInput("zip_code", label = h3("Enter Zip score"), value = "10001", width = NULL, placeholder = NULL)


max_score = nyc_inspections %>%  distinct(score)%>% max()
min_score = nyc_inspections %>% distinct(score)%>% min()

# sliderInput widget
sliderInput("score_range", label = h3("Choose score range"), min = min_score, 
        max = max_score, value = c(0, 25))
```


Row
-----------------------------------------------------------------------

### Chart A

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
nyc_inspections %>%
  filter(!boro == "Missing", 
         zipcode == input$zip_code, 
         score %in% input$score_range[1]:input$score_range[2]) %>%
  mutate(boro = as.factor(boro),
         boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
})
```

### Chart C

```{r}

```

