---
title: "shiny_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(stringr)
library(forcats)
library(tidytext) 
library(ggridges)
library(shiny)
```

```{r}
library(httr)
library(jsonlite)
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() %>%
  drop_na() %>%
  mutate(score = as.numeric(score)) %>%
  select(score, boro, zipcode, cuisine_description, violation_description)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
zipcodes = nyc_inspections %>% distinct(zipcode) %>% pull()

# selectInput widget
selectInput("zip_choice", label = h3("Select zipcode"),
            choices = zipcodes, selected = "10001")

max_score = nyc_inspections %>%  distinct(score)%>% max()
min_score = nyc_inspections %>% distinct(score)%>% min()

# sliderInput widget
sliderInput("score_range", label = h3("Choose score range"), min = min_score, 
        max = max_score, value = c(0, 25))
```


Row
-----------------------------------------------------------------------

### A.Density Plot of Score vs Top 5 Kinds of Cuisine 

```{r}
renderPlotly({
top_5_cuisine = nyc_inspections %>%
  filter(zipcode == input$zip_choice, 
         score %in% input$score_range[1]:input$score_range[2])%>%
  select(score, cuisine_description) %>%
  count(cuisine_description, sort = TRUE) %>%
  top_n(5) %>%
  select(cuisine_description)

cuisine_density = nyc_inspections %>%
  inner_join(., top_5_cuisine) %>%
  filter(zipcode == input$zip_choice, 
         score %in% input$score_range[1]:input$score_range[2])%>%
  select(score, cuisine_description) %>%
  mutate(score=as.numeric(score))%>%
  ggplot(aes(score, fill = cuisine_description)) + 
  geom_density(alpha = 0.2)
  
ggplotly(cuisine_density)
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### B.Boxplot of Score vs Boro

```{r}
renderPlotly({
nyc_inspections %>%
  filter(!boro == "Missing", 
         zipcode == input$zip_choice, 
         score %in% input$score_range[1]:input$score_range[2]) %>%
  mutate(boro = as.factor(boro),
         boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
})
```

### C.Top 10 Words Appearing in Inspections

```{r}
renderPlotly({
inspection_words = nyc_inspections %>% 
  filter(zipcode == input$zip_choice, score %in% input$score_range[1]:input$score_range[2])%>%
  unnest_tokens(word, violation_description) %>%
  anti_join(stop_words)

inspection_words %>%
  count(word, sort = TRUE) %>%
  top_n(10) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  plot_ly(x =~ word, y = ~n, color =~ word, type = "bar", colors = "Set1")
})
```

